export { default as Navbar } from "./Navbar/Navbar";
export { default as Landing } from "./Landing/Landing";
export { default as Destinations } from "./Destinations/Destinations";
export { default as Featured } from "./Featured/Featured";
export { default as About } from "./About/About";
export { default as Movies } from "./Filter/Movies";
export { default as Blogs } from "./Blogs/Blogs";
export { default as Footer } from "./Footer/Footer";
export { default as Hidden } from "./Hidden/Hidden";
